### ISSUE TITLE
Issue in context.py example

### ISSUE THREAD

**Issue by Jaleel-VS** [demian-wolf/ReversoAPI#4]
I think `reverso_api import ReversoContextAPI` should be
 `reverso_api.context import ReversoContextAPI`

**Comment by demian-wolf** [comment]
Before I have reorganized the package structure a few days ago, `reverso_api.context` was the only way to import ReversoContextAPI.

Actually, it still is in the v0.0.1b3 release (the latest one, at the moment of writing this). It looks like you are asking this question because you got `ImportError` while trying to run the already changed example with that release :)

With the latest commits, I have added another, now preferred, way for importing stuff from reverso_api: `from reverso_api import ...`. That said, `from reverso_api.context import ...` will continue to work with future releases for backward compatibility.
